#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_SOURCES="$ROOT_DIR/NEARPrivateChat"
CHAT_STORE="$ROOT_DIR/NEARPrivateChat"
CHAT_STREAMING_RUNTIME="$ROOT_DIR/NEARPrivateChat/App/State/ChatStore+StreamingRuntime.swift"
APP_SHELL="$ROOT_DIR/NEARPrivateChat"
MOBILE_STACK="$ROOT_DIR/NEARPrivateChat/Features/Agent/IronclawMobileStack.swift"
PRIVATE_API="$ROOT_DIR/NEARPrivateChat/Core/API/PrivateChatAPI.swift"
API_CLIENT="$ROOT_DIR/NEARPrivateChat/Core/API/APIClient.swift"
FILE_API="$ROOT_DIR/NEARPrivateChat/Core/API/FileAPI.swift"
MESSAGE_API="$ROOT_DIR/NEARPrivateChat/Core/API/MessageAPI.swift"
MESSAGE_LOAD_COORDINATOR="$ROOT_DIR/NEARPrivateChat/Features/Chat/ChatMessageLoadCoordinator.swift"
FILE_CACHE="$ROOT_DIR/NEARPrivateChat/Core/Persistence/FileCache.swift"
SESSION_STORE="$ROOT_DIR/NEARPrivateChat/Core/Auth/SessionStore.swift"
AUTH_VIEW="$ROOT_DIR/NEARPrivateChat/Features/Auth/AuthView.swift"
IRONCLAW_API="$ROOT_DIR/NEARPrivateChat/Core/API/IronclawAPI.swift"
MODELS="$ROOT_DIR/NEARPrivateChat"
CHAT_MODELS="$ROOT_DIR/NEARPrivateChat/Features/Chat/ChatModels.swift"
CHAT_IMPORT="$ROOT_DIR/NEARPrivateChat/Core/Export/ChatImport.swift"
CONVERSATION_EXPORT="$ROOT_DIR/NEARPrivateChat/Core/Export/ConversationExport.swift"
CONVERSATION_RENDERED_EXPORT="$ROOT_DIR/NEARPrivateChat/Core/Export/ConversationExport+RenderedFormats.swift"
WEB_GROUNDING="$ROOT_DIR/NEARPrivateChat/Core/Services/WebGroundingService.swift"
KEYCHAIN_STORE="$ROOT_DIR/NEARPrivateChat/Core/Auth/KeychainStore.swift"
APP_FILE="$ROOT_DIR/NEARPrivateChat"
GATEWAY_SCRIPT="$ROOT_DIR/scripts/start-ironclaw-gateway.sh"
HTTPS_BRIDGE_SCRIPT="$ROOT_DIR/scripts/start-ironclaw-https-bridge.sh"
TOKEN_HELPER="$ROOT_DIR/scripts/lib/ironclaw-token.sh"
LOCAL_CONFIG_HELPER="$ROOT_DIR/scripts/lib/ironclaw-local-config.sh"
IRONCLAW_PREFLIGHT="$ROOT_DIR/scripts/ironclaw-preflight.sh"
IRONCLAW_CODE_SMOKE="$ROOT_DIR/scripts/ironclaw-code-agent-smoke.sh"
IRONCLAW_RESEARCH_SMOKE="$ROOT_DIR/scripts/ironclaw-research-smoke.sh"
IRONCLAW_WORKSTATION_SMOKE="$ROOT_DIR/scripts/ironclaw-workstation-smoke.sh"
SIMULATOR_SEED_SCRIPT="$ROOT_DIR/scripts/seed-simulator-ironclaw.sh"
ATTACHMENT_SMOKE="$ROOT_DIR/scripts/attachment-upload-smoke.sh"
PROJECT_FILE="$ROOT_DIR/NEARPrivateChat.xcodeproj/project.pbxproj"
SCHEME_FILE="$ROOT_DIR/NEARPrivateChat.xcodeproj/xcshareddata/xcschemes/NEARPrivateChat.xcscheme"
CORE_TESTS="$ROOT_DIR/NEARPrivateChatTests/PrivateChatCoreTests.swift"
TESTS_ROOT="$ROOT_DIR/NEARPrivateChatTests"
PRIVACY_MANIFEST="$ROOT_DIR/NEARPrivateChat/PrivacyInfo.xcprivacy"
IGNORE_FILE="$ROOT_DIR/.gitignore"

require_source() {
  local file="$1"
  local pattern="$2"
  local label="$3"
  if ! rg -q "$pattern" "$file"; then
    echo "missing $label: $pattern" >&2
    exit 1
  fi
}

forbid_source() {
  local file="$1"
  local pattern="$2"
  local label="$3"
  if rg -q "$pattern" "$file"; then
    echo "unexpected $label: $pattern" >&2
    exit 1
  fi
}

line_number() {
  local pattern="$1"
  local file="$2"
  rg -n "$pattern" "$file" | head -1 | cut -d: -f1
}

require_source "$CHAT_STORE" "selectedModel != ModelOption\\.ironclawMobileModelID" "mobile runtime bypass from eager hosted routing"
require_source "$CHAT_STORE" "hostedIronclawContextSection" "hosted agent project context"
require_source "$CHAT_STORE" "iOS project context" "project context prompt section"
require_source "$CHAT_STORE" "nearai_web_search first" "research tool instruction"
require_source "$CHAT_STORE" "Use grep/read_file/apply_patch" "agent edit tool instruction"
require_source "$CHAT_STORE" "Keep hosted runs phone-safe and bounded" "bounded hosted run instruction"
require_source "$CHAT_STORE" "shallow clones" "shallow clone instruction"
require_source "$CHAT_STORE" "wrap long commands with timeout" "timeout instruction"
require_source "$CHAT_STORE" "visibleLines" "visible mobile tool detail output"
require_source "$CHAT_STORE" "coding agent" "explicit coding-agent trigger"
require_source "$CHAT_STORE" "run tests" "explicit test trigger"
require_source "$CHAT_STORE" "github" "GitHub repo trigger"
require_source "$CHAT_STORE" "review the repo" "repo review trigger"
require_source "$CHAT_STORE" "phoneAgentMissionPromptIfNeeded" "composer-to-agent mission wrapper"
require_source "$CHAT_STORE" "Hosted IronClaw Mission" "agent mission prompt title"
require_source "$CHAT_STORE" "Mission brief from phone" "phone mission brief prompt section"
require_source "$CHAT_STORE" "Do not commit, push, or open a PR unless I explicitly ask" "phone-safe git write guard"
require_source "$CHAT_STORE" "IronClaw skill routing" "phone mission skill-routing section"
require_source "$CHAT_STORE" "Research To Code" "research-to-code mission classification"
require_source "$CHAT_STORE" "Security Review" "security review mission classification"
require_source "$CHAT_STORE" "QA Review" "QA review mission classification"
require_source "$CHAT_STORE" "Product Prioritization" "product prioritization mission classification"
require_source "$CHAT_STORE" "Decision Capture" "decision capture mission classification"
require_source "$CHAT_STORE" "product-prioritization" "IronClaw product prioritization skill hint"
require_source "$CHAT_STORE" "decision-capture" "IronClaw decision capture skill hint"
require_source "$CHAT_STORE" "organizePhoneAgentConversationIfNeeded" "agent run auto-organization"
require_source "$CHAT_STORE" "firstRepoURL" "repo URL detection for agent organization"
require_source "$CHAT_STORE" "repoProjectName" "repo project naming for agent organization"
require_source "$CHAT_STORE" "repoRootURL" "canonical repo root saved for agent organization"
require_source "$CHAT_STORE" "repoTaskLinkTitle" "issue and PR task link labels"
require_source "$CHAT_STORE" "Issue #" "GitHub issue link label"
require_source "$CHAT_STORE" "PR #" "GitHub PR link label"
require_source "$CHAT_STORE" "Repo-backed Agent Project" "repo-backed project instructions"
require_source "$CHAT_STORE" "agentMissionConversationTitle" "agent mission title cleanup"
require_source "$MOBILE_STACK" "lowercased\\.contains\\(\"github\"\\)" "GitHub URL project-link capture"
require_source "$MOBILE_STACK" "for https://" "project names trimmed before repo URLs"
require_source "$MOBILE_STACK" "repoProjectNameFromURL" "repo URL project-name derivation"
require_source "$MOBILE_STACK" "set up a repo-backed project" "repo URL project creation action"
require_source "$MOBILE_STACK" "projectNameLooksLikeURL" "URL-like project name guard"
require_source "$MOBILE_STACK" "promptNeedsFreshResearch" "fresh research auto-source detector"
require_source "$MOBILE_STACK" "The user asked for latest or current information" "fresh research mode action"
require_source "$APP_SHELL" "HomeStreamsCopy\\.subtitle" "quiet Streams route subtitle"
require_source "$APP_SHELL" "HomeSurfaceBackground" "coherent blue home surface"
require_source "$APP_SHELL" "AccountToolbarButton" "account moved to top-right home affordance"
require_source "$APP_SHELL" "WorkspaceCommandHeader" "blue command-card home system"
require_source "$APP_SHELL" "title: \"Ask\"" "Ask remains the primary home action"
require_source "$MODELS" "appSymbolBlueBackground" "coherent blue row symbol tint"
require_source "$MODELS" "UserSetupProfile" "first-run setup profile model"
require_source "$MODELS" "UserSetupUseCase" "first-run setup use-case questions"
require_source "$MODELS" "IronclawSkillCatalog" "upstream IronClaw skill catalog"
require_source "$MODELS" "llm-council" "LLM Council skill in mobile catalog"
require_source "$MODELS" "commitment-triage" "commitment skill in mobile catalog"
require_source "$MODELS" "portfolio" "portfolio skill in mobile catalog"
require_source "$CHAT_STORE" "applySetupProfile" "first-run setup applies app defaults"
require_source "$CHAT_STORE" "IronclawSkillCatalog\\.promptSection" "agent mission uses skill catalog"
require_source "$MODELS" "Do not print the routing" "skill routing stays internal"
require_source "$APP_FILE" "UserSetupView" "first-run setup flow"
require_source "$APP_FILE" "Tune defaults for new chats" "blue setup hero"
require_source "$APP_SHELL" "Rerun Setup" "account can rerun setup"
require_source "$APP_SHELL" "Run Agent" "compact agent workspace entry"
require_source "$APP_SHELL" "AgentWorkspaceView" "dedicated agent workspace view"
require_source "$APP_SHELL" "ProjectContextSummaryBar" "project context segmented lanes"
require_source "$APP_SHELL" "SharedWithMeView" "shared-with-me native inbox"
require_source "$APP_SHELL" "Export TXT" "native text transcript export"
require_source "$APP_SHELL" "Export JSON" "native JSON transcript export"
require_source "$APP_SHELL" "Export Archive JSON" "native archived-chat file export"
require_source "$APP_SHELL" "Import Chats" "native chat import action"
require_source "$APP_SHELL" "Grant Access" "native direct organization share management"
require_source "$APP_SHELL" "Share Groups" "native share access list"
require_source "$APP_SHELL" "grantOrganizationShare" "native organization sharing"
require_source "$APP_SHELL" "Share Group" "native share group sharing"
require_source "$APP_SHELL" "Create Group" "native share group creation"
require_source "$APP_SHELL" "Edit Share Group" "native share group editing"
require_source "$APP_SHELL" "Save Group" "native share group save action"
require_source "$APP_SHELL" "ProjectFilesView" "native file library"
require_source "$APP_SHELL" "RemoteFilePreview" "native file preview sheet"
require_source "$APP_SHELL" "attachRemoteFileToPrompt" "library file prompt attachment"
require_source "$APP_SHELL" "addRemoteFileToSelectedProject" "library file project attachment"
require_source "$CONVERSATION_EXPORT" "ConversationExportDocument" "export document module"
require_source "$MODELS" "RemoteFileInfo" "remote file model"
require_source "$PRIVATE_API" "fetchSharedWithMe" "shared-with-me API parity"
require_source "$PRIVATE_API" "addItemsToConversation" "chat import item API parity"
require_source "$PRIVATE_API" "createDirectShare" "direct share API parity"
require_source "$PRIVATE_API" "createOrganizationShare" "organization share API parity"
require_source "$PRIVATE_API" "fetchShareGroups" "share group list API parity"
require_source "$PRIVATE_API" "createShareGroup" "share group create API parity"
require_source "$PRIVATE_API" "updateShareGroup" "share group update API parity"
require_source "$PRIVATE_API" "deleteShareGroup" "share group delete API parity"
require_source "$PRIVATE_API" "fetchFileContent" "file content API parity"
require_source "$CHAT_STORE" "refreshSharedWithMe" "shared-with-me store refresh"
require_source "$CHAT_STORE" "importChats\\(from" "native chat import store action"
require_source "$CHAT_STORE" "openSharedPreviewForWriting" "writable shared conversation open action"
require_source "$CHAT_STORE" "knownCanWrite" "shared preview carries known write permission"
require_source "$CHAT_STORE" "grantDirectShare" "direct share store action"
require_source "$CHAT_STORE" "grantOrganizationShare" "organization share store action"
require_source "$CHAT_STORE" "grantGroupShare" "group share store action"
require_source "$CHAT_STORE" "refreshShareGroups" "share group refresh"
require_source "$CHAT_STORE" "updateShareGroup\\(" "share group edit store action"
require_source "$CHAT_STORE" "refreshRemoteFiles" "file library refresh"
require_source "$CHAT_STORE" "previewRemoteFile" "file preview store action"
require_source "$CHAT_STORE" "attachRemoteFileToPrompt" "remote file prompt action"
require_source "$CHAT_STORE" "addRemoteFileToSelectedProject" "remote file project action"
require_source "$CHAT_STORE" "initiator: \"regenerate\"" "regenerate response initiator"
require_source "$CHAT_STORE" "initiator: \"edit_message\"" "edit-message response initiator"
require_source "$CHAT_STORE" "editAndResend" "edit-message branch store action"
require_source "$CHAT_STORE" "activeConversationPathItems" "response branch path selection"
require_source "$CHAT_STORE" "selectResponseVariant" "response variant picker store action"
require_source "$CHAT_STORE" "branchVariantMetadata" "response sibling metadata builder"
require_source "$CHAT_STORE" "councilModelIDs" "LLM Council model selection persistence"
require_source "$CHAT_STORE" "useDefaultCouncilLineup" "LLM Council default lineup action"
require_source "$CHAT_STORE" "withTaskGroup\\(of: CouncilStreamResult\\.self" "LLM Council parallel stream fan-out"
require_source "$CHAT_STORE" "synthesisPrompt" "LLM Council synthesis prompt"
require_source "$CHAT_STORE" "promptRequestsCouncil" "natural-language LLM Council intent detection"
require_source "$CHAT_STORE" "routeCouncilIfNeeded" "smart LLM Council prompt routing"
require_source "$CHAT_STORE" "LLM Council selected for a multi-model answer" "smart LLM Council routing banner"
require_source "$APP_SHELL" "Choose Council Models" "native LLM Council picker card"
require_source "$APP_SHELL" "CouncilResponseGroup" "native grouped council response UI"
require_source "$APP_SHELL" "Import Chats" "account chat import action"
require_source "$APP_SHELL" "Export Archive JSON" "archived chat export action"
require_source "$APP_SHELL" "ShareGroupsView" "standalone share group editing"
require_source "$APP_SHELL" "Share Groups" "account share group management action"
forbid_source "$APP_SHELL" "title: \"Workflows\"" "home workflows project row"
forbid_source "$APP_SHELL" "Variants · council" "workflow taxonomy subtitle"
require_source "$MODELS" "councilBatchID" "conversation message council grouping metadata"
require_source "$MODELS" "MessageBranchVariant" "conversation message branch variant metadata"
require_source "$APP_SHELL" "ResponseVariantPicker" "native response variant picker UI"
require_source "$CHAT_IMPORT" "ChatImportBuilder" "native chat import parser"
require_source "$CHAT_IMPORT" "LegacyChatHistory" "legacy chat import format"
require_source "$MESSAGE_API" "case initiator" "responses initiator payload field"
require_source "$APP_SHELL" "Edit & Branch" "edit-message branch UI"
require_source "$APP_SHELL" "Open shared conversation for writing" "shared write-access UI action"
require_source "$APP_SHELL" "Export PDF" "conversation PDF export action"
require_source "$CONVERSATION_EXPORT" "case pdf" "PDF export format"
require_source "$CONVERSATION_RENDERED_EXPORT" "UIGraphicsPDFRenderer" "native paginated PDF renderer"
require_source "$APP_SHELL" "ProjectSectionLabel\\(\"Sources\"\\)" "project sources lane"
require_source "$APP_SHELL" "ProjectAddFilePill" "project files lane"
require_source "$APP_SHELL" "ProjectSectionLabel\\(\"Instructions\"\\)" "project instructions lane"
require_source "$APP_SHELL" "ProjectSectionLabel\\(\"Saved answers\"\\)" "project notes lane"
require_source "$APP_SHELL" "PublicLinkPreviewView" "public link preview before publish"
require_source "$APP_SHELL" "pendingSensitiveShareGrant" "public link publish review action"
require_source "$APP_SHELL" "Run Agent" "simplified smart agent launcher"
require_source "$APP_SHELL" "agentReadinessTitle" "compact agent readiness copy"
require_source "$APP_SHELL" "IronclawSkillCatalog\\.promptSection" "single auto agent mode"
require_source "$APP_SHELL" "agentSkillPreview" "agent skill routing preview"
require_source "$APP_SHELL" "sourceModeOptionsDialog" "simplified composer context choices"
require_source "$APP_SHELL" "Agent mission brief" "agent mission brief input"
require_source "$APP_SHELL" "PromptSuggestion" "quick-start prompt suggestions"
require_source "$APP_SHELL" "homeLaunchActionTitle" "single agent launch action"
require_source "$APP_SHELL" "ToolbeltCapability" "agent capability detection"
require_source "$APP_SHELL" "nearai_web_search" "agent toolbelt web capability"
require_source "$APP_SHELL" "No project selected" "agent launcher project context panel"
require_source "$APP_SHELL" "Open Context" "agent launcher context management action"
require_source "$APP_SHELL" "Agent mission:" "concise visible agent prompt"
require_source "$APP_SHELL" "selectModel\\(ModelOption\\.ironclawModelID\\)" "agent launcher forces hosted route"
require_source "$APP_SHELL" "chatStore\\.sendDraft\\(\\)" "agent launcher dispatches in one tap"
require_source "$APP_SHELL" "researchModeEnabled = false" "non-research agent launch avoids forced web search"
require_source "$APP_SHELL" "suggestedSkills" "general agent mission"
require_source "$CHAT_STORE" "strippedAgentLaunchPrefix" "agent launcher prefix hidden from routed prompt"
require_source "$CHAT_STORE" "webGroundingPrompt" "web search uses clean agent mission brief"
require_source "$CHAT_STORE" "text: text" "visible user prompt stays concise"
require_source "$WEB_GROUNDING" "latest\\|recent\\|current.*news\\|updates\\|developments" "latest AI news query cleanup"
require_source "$WEB_GROUNDING" "sourceQualityScore" "web source quality ranking"
require_source "$WEB_GROUNDING" "preferredSourceHosts" "trusted source preference"
require_source "$WEB_GROUNDING" "lowQualityHostFragments" "low-quality source penalty"
require_source "$APP_SHELL" "strippedAgentLaunchPrefix" "evidence strip hides internal agent wrapper"
require_source "$APP_SHELL" "No output received" "stale agent run status"
require_source "$APP_SHELL" "hosted run may have stalled" "stale agent recovery copy"
require_source "$APP_SHELL" "Stop stalled IronClaw run" "stale streaming stop action"
require_source "$GATEWAY_SCRIPT" 'GATEWAY_HOST="\$\{GATEWAY_HOST:-127\.0\.0\.1\}"' "localhost-only IronClaw gateway default"
require_source "$GATEWAY_SCRIPT" "secrets\\.token_urlsafe\\(32\\)" "random IronClaw gateway token generation"
require_source "$GATEWAY_SCRIPT" "IRONCLAW_STATE_DIR" "gateway secret state directory outside repo"
require_source "$GATEWAY_SCRIPT" "ironclaw-gateway\\.env" "gateway env file indirection"
require_source "$GATEWAY_SCRIPT" "write_export\\(\\)" "gateway writes protected env file without child-process secret env"
require_source "$GATEWAY_SCRIPT" 'screen -dmS "\$SCREEN_NAME" /bin/zsh "\$RUNNER_FILE" "\$ENV_FILE"' "gateway screen launch without argv secrets"
require_source "$GATEWAY_SCRIPT" "IRONCLAW_ALLOW_NONLOCAL_BIND" "explicit non-local gateway bind override"
require_source "$GATEWAY_SCRIPT" "IRONCLAW_AUTO_APPROVE" "explicit IronClaw auto-approve override"
require_source "$HTTPS_BRIDGE_SCRIPT" "public tunnel without a private random gateway token" "public tunnel token guard"
require_source "$HTTPS_BRIDGE_SCRIPT" "IRONCLAW_STATE_DIR" "https bridge reads token outside repo"
require_source "$TOKEN_HELPER" "IRONCLAW_REMOTE_TOKEN_FILE" "remote token file discovery"
require_source "$TOKEN_HELPER" "ironclaw-gateway\\.token" "protected remote token file candidate"
require_source "$LOCAL_CONFIG_HELPER" "local/ironclaw\\.env" "ignored repo-local IronClaw config"
require_source "$IRONCLAW_PREFLIGHT" "load_ironclaw_local_config" "preflight loads local IronClaw config"
require_source "$IRONCLAW_PREFLIGHT" "discover_remote_gateway_token" "preflight uses token-file discovery"
require_source "$SIMULATOR_SEED_SCRIPT" "discover_remote_gateway_token" "simulator seeding uses token-file discovery"
require_source "$SIMULATOR_SEED_SCRIPT" "ALLOW_SIMULATOR_TOKEN_SEED" "explicit simulator token seed consent"
require_source "$IRONCLAW_CODE_SMOKE" "discover_remote_gateway_token" "code agent smoke uses token-file discovery"
require_source "$IRONCLAW_RESEARCH_SMOKE" "discover_remote_gateway_token" "research smoke uses token-file discovery"
require_source "$IRONCLAW_WORKSTATION_SMOKE" "discover_remote_gateway_token" "workstation smoke uses token-file discovery"
require_source "$IGNORE_FILE" "/build/" "build output ignored"
require_source "$IGNORE_FILE" "\\*\\.token" "token artifacts ignored"
require_source "$ATTACHMENT_SMOKE" "APP_PATH" "attachment smoke app path install fallback"
require_source "$ATTACHMENT_SMOKE" "simctl install" "attachment smoke auto-installs built app"
forbid_source "$GATEWAY_SCRIPT" 'GATEWAY_AUTH_TOKEN="\$\{GATEWAY_AUTH_TOKEN:-near-private-ios-local-dev-token\}"' "default IronClaw gateway token"
forbid_source "$HTTPS_BRIDGE_SCRIPT" 'GATEWAY_AUTH_TOKEN="\$\{GATEWAY_AUTH_TOKEN:-near-private-ios-local-dev-token\}"' "default IronClaw bridge token"
forbid_source "$GATEWAY_SCRIPT" "run --no-onboard --auto-approve" "unconditional IronClaw auto-approve"
forbid_source "$GATEWAY_SCRIPT" 'screen -dmS "\$SCREEN_NAME" /usr/bin/env' "argv-visible gateway secret environment"
forbid_source "$GATEWAY_SCRIPT" 'GATEWAY_AUTH_TOKEN="\$GATEWAY_AUTH_TOKEN" \\' "gateway token child-process environment"
forbid_source "$IRONCLAW_PREFLIGHT" "/proc/\\[0-9\\]" "preflight process-environment token scrape"
forbid_source "$SIMULATOR_SEED_SCRIPT" "/proc/\\[0-9\\]" "simulator seed process-environment token scrape"
forbid_source "$IRONCLAW_CODE_SMOKE" "/proc/\\[0-9\\]" "code smoke process-environment token scrape"
forbid_source "$IRONCLAW_RESEARCH_SMOKE" "/proc/\\[0-9\\]" "research smoke process-environment token scrape"
forbid_source "$IRONCLAW_WORKSTATION_SMOKE" "/proc/\\[0-9\\]" "workstation smoke process-environment token scrape"
forbid_source "$IRONCLAW_PREFLIGHT" "dangwalvaidy|baremetal3|agent-private-key" "personal IronClaw preflight defaults"
forbid_source "$SIMULATOR_SEED_SCRIPT" "dangwalvaidy|baremetal3|agent-private-key" "personal simulator seed defaults"
forbid_source "$IRONCLAW_CODE_SMOKE" "dangwalvaidy|baremetal3|agent-private-key" "personal code smoke defaults"
forbid_source "$IRONCLAW_RESEARCH_SMOKE" "dangwalvaidy|baremetal3|agent-private-key" "personal research smoke defaults"
forbid_source "$IRONCLAW_WORKSTATION_SMOKE" "dangwalvaidy|baremetal3|agent-private-key" "personal workstation smoke defaults"
require_source "$PRIVATE_API" "authURL\\(for provider: OAuthProvider, state" "auth URL state nonce"
require_source "$PRIVATE_API" "expectedState" "auth callback expected state validation"
require_source "$MESSAGE_API" "response stream ended before the server sent response.completed" "truncated stream failure"
require_source "$SESSION_STORE" "createPendingAuthRequest" "pending auth state request"
require_source "$SESSION_STORE" "requirePendingAuthRequest" "auth callback requires pending state"
require_source "$SESSION_STORE" "clearPendingAuthState" "auth state cleanup"
require_source "$AUTH_VIEW" "SecureField\\(\"session token\"" "secure developer token entry"
require_source "$AUTH_VIEW" "authTokenValidationMessage" "session token validation gate"
require_source "$CHAT_STORE" "Finish or cancel the current response" "stream navigation lock"
require_source "$MESSAGE_LOAD_COORDINATOR" "generation" "conversation load generation guard"
require_source "$CHAT_STORE" "cancelMessageLoad" "conversation load cancellation"
require_source "$MESSAGE_LOAD_COORDINATOR" "canApplyMessageLoad" "stale conversation load apply guard"
require_source "$CHAT_STORE" "mergedMessages\\(remoteMessages" "remote/local message merge"
require_source "$FILE_CACHE" "fileURL\\(filename:" "file-backed local cache storage"
require_source "$FILE_CACHE" "completeFileProtection" "cache file protection"
forbid_source "$FILE_CACHE" "UserDefaults\\.standard\\.set\\(data, forKey: legacyDefaultsKey\\)" "private cache UserDefaults write fallback"
require_source "$KEYCHAIN_STORE" "kSecAttrAccessibleWhenUnlockedThisDeviceOnly" "narrow Keychain accessibility"
require_source "$CHAT_STORE" "Response failed:" "visible partial stream failure"
require_source "$CHAT_STORE" "Task\\.detached\\(priority: \\.userInitiated" "off-main import/PDF work"
require_source "$CHAT_STORE" "Attached readable text from" "honest PDF text attachment metadata"
require_source "$API_CLIENT" "readableRequest" "public read unauth retry helper"
require_source "$API_CLIENT" "conversationPath" "safe conversation path builder"
require_source "$PRIVATE_API" "isSafeAPIPathID" "API path segment validation"
require_source "$FILE_API" "Task\\.detached\\(priority: \\.userInitiated" "off-main plain file upload read"
require_source "$API_CLIENT" "maxUploadBytes" "API upload size cap"
require_source "$CHAT_MODELS" "sanitizedURLString" "provider source URL scheme filter"
require_source "$APP_SHELL" "requestDeleteConversation" "delete confirmation request path"
require_source "$APP_SHELL" "Delete Permanently" "permanent delete confirmation dialog"
require_source "$APP_SHELL" "Open external shortcut\\?" "external deep link confirmation"
require_source "$APP_SHELL" "\\[\\.links, \\.files, \\.all\\]" "saved links composer source mode"
require_source "$APP_SHELL" "onRunSetupAgain" "setup rerun binding"
require_source "$CHAT_STORE" "isAllowedSharedConversationURL" "shared-link host allowlist"
require_source "$CHAT_STORE" "pendingExternalDeepLink" "external deep link pending confirmation state"
require_source "$CHAT_STORE" "isSafeRawConversationID" "broad safe raw shared ID parser"
require_source "$CHAT_IMPORT" "ChatImportLimits" "chat import size and count limits"
require_source "$IRONCLAW_API" "IRONCLAW_ALLOW_INSECURE_ENDPOINT" "explicit debug override for insecure IronClaw endpoints"
require_source "$MODELS" "ChatSourceRoutingSemantics" "source/focus route semantics model"
require_source "$MODELS" "safeURL" "safe source URL rendering"
require_source "$MODELS" "modelNativeWebToolPolicy" "native web tool policy separated from source packs"
require_source "$MODELS" "appWebGroundingPolicy" "app-side grounding policy separated from native tools"
forbid_source "$IRONCLAW_API" "consumeEvents" "dead IronClaw SSE consumer"
require_source "$IRONCLAW_API" "api/webchat/v2/threads" "Reborn WebChat v2 route connection test"
require_source "$IRONCLAW_API" "IronClaw failed on this turn" "failed IronClaw state stays failed"
require_source "$MODELS" 'case "system", "developer"' "developer role decode"
require_source "$MODELS" 'case "assistant", "tool"' "tool role decode"
require_source "$CHAT_IMPORT" 'case "developer"' "developer role import normalization"
require_source "$CHAT_IMPORT" 'case "tool"' "tool role import normalization"
require_source "$PROJECT_FILE" "NEARPrivateChatTests" "XCTest target"
require_source "$SCHEME_FILE" "TestableReference" "scheme test action"
require_source "$TESTS_ROOT" "testAuthCallbackRejectsMissingOrWrongState" "auth state unit test"
require_source "$TESTS_ROOT" "testChatImportNormalizesDeveloperAndToolRoles" "role import unit test"
require_source "$TESTS_ROOT" "testConversationIDParserAcceptsSafeRawIDsAndLinks" "raw shared ID parser unit test"
require_source "$TESTS_ROOT" "testRemoteMessagesMergeLocalExternalTurnsOnly" "local external merge unit test"
require_source "$TESTS_ROOT" "testResponseStreamParserHandlesCoreEvents" "response stream parser core event test"
require_source "$TESTS_ROOT" "testResponseStreamParserHandlesToolAndFailureEvents" "response stream parser tool/failure test"
require_source "$TESTS_ROOT" "testSourceRoutingSemanticsNearPrivateSeparatesLinksFromNativeWebTool" "NEAR Private source semantics unit test"
require_source "$TESTS_ROOT" "testSourceRoutingSemanticsNearCloudUsesAppGroundingWithoutNativeTools" "NEAR Cloud source semantics unit test"
require_source "$TESTS_ROOT" "testSourceRoutingSemanticsIronclawMobileAndHostedRoutes" "IronClaw source semantics unit test"
require_source "$PRIVACY_MANIFEST" "NSPrivacyTracking" "privacy manifest"
require_source "$PRIVACY_MANIFEST" "NSPrivacyAccessedAPICategoryUserDefaults" "UserDefaults required-reason privacy manifest"
require_source "$PRIVACY_MANIFEST" "CA92\\.1" "UserDefaults required reason"
require_source "$ROOT_DIR/WEB_PARITY.md" "Subscriptions/plans and low-balance UX.*Implemented" "billing parity doc"

if rg -q "Playbook|workflowChip|Setup / Explore|Build / Debug|Deep Research|Repo / PR|Infer tools from the brief|commands/sources|Auto workflow" "$APP_SHELL"; then
  echo "agent launcher should not expose playbooks or bottom contract copy" >&2
  exit 1
fi

if rg -q "Evidence with dated sources when research or web is used" "$APP_SHELL"; then
  echo "non-research launcher prompt still contains broad web/source trigger copy" >&2
  exit 1
fi

if rg -q "EmptyChatModeDock|quickSuggestionPills|emptyStateStatusLine" "$APP_SHELL"; then
  echo "empty chat should stay quiet; remove duplicated mode dock, prompt pills, and status chip copy" >&2
  exit 1
fi

tool_line="$(line_number "let toolResults = await executeIronclawMobileToolCalls" "$CHAT_STREAMING_RUNTIME")"
handoff_line="$(line_number "if Self\\.promptNeedsRemoteWorkstation\\(text\\), ironclawRemoteWorkstationAvailable" "$CHAT_STREAMING_RUNTIME")"
if [[ -z "$tool_line" || -z "$handoff_line" ]]; then
  echo "could not locate mobile tool execution or hosted handoff" >&2
  exit 1
fi

if (( tool_line >= handoff_line )); then
  echo "mobile tool execution must happen before hosted handoff; tool_line=$tool_line handoff_line=$handoff_line" >&2
  exit 1
fi

echo "ironclaw mobile agent source smoke ok"
