#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IRONCLAW_REPO="${IRONCLAW_REPO:-"$ROOT_DIR/../ironclaw"}"
IRONCLAW_BIN="${IRONCLAW_BIN:-"$IRONCLAW_REPO/target/debug/ironclaw"}"
SCREEN_NAME="${IRONCLAW_SCREEN_NAME:-ironclaw-ios}"
STATE_DIR="${IRONCLAW_STATE_DIR:-"$HOME/Library/Application Support/NEARPrivateChat/IronClaw"}"
LOG_DIR="${IRONCLAW_LOG_DIR:-"$HOME/Library/Logs/NEARPrivateChat"}"
LOG_FILE="$LOG_DIR/ironclaw-gateway.log"
PID_FILE="$STATE_DIR/ironclaw-gateway.pid"
TOKEN_FILE="$STATE_DIR/ironclaw-gateway.token"
ENV_FILE="$STATE_DIR/ironclaw-gateway.env"
RUNNER_FILE="$STATE_DIR/run-ironclaw-gateway.sh"
DEFAULT_DEV_TOKEN="near-private-ios-local-dev-token"

GATEWAY_HOST="${GATEWAY_HOST:-127.0.0.1}"
GATEWAY_PORT="${GATEWAY_PORT:-3000}"
GATEWAY_AUTH_TOKEN="${GATEWAY_AUTH_TOKEN:-}"
NEARAI_MODEL="${NEARAI_MODEL:-Qwen/Qwen3.5-122B-A10B}"
IRONCLAW_AUTO_APPROVE="${IRONCLAW_AUTO_APPROVE:-0}"
LAN_HOST="${IRONCLAW_LAN_HOST:-$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)}"
HEALTH_HOST="$GATEWAY_HOST"
if [[ "$HEALTH_HOST" == "0.0.0.0" ]]; then
  HEALTH_HOST="127.0.0.1"
fi

umask 077
mkdir -p "$LOG_DIR" "$STATE_DIR"
chmod 700 "$STATE_DIR"

if [[ -z "$GATEWAY_AUTH_TOKEN" ]]; then
  GATEWAY_AUTH_TOKEN="$(
    python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
  )"
fi

if [[ "$GATEWAY_AUTH_TOKEN" == "$DEFAULT_DEV_TOKEN" ]]; then
  echo "Refusing to start IronClaw with the old shared default gateway token." >&2
  echo "Unset GATEWAY_AUTH_TOKEN to generate a random token, or provide a private token explicitly." >&2
  exit 1
fi

NEARAI_SESSION_TOKEN_VALUE="${NEARAI_SESSION_TOKEN:-}"
if [[ -z "$NEARAI_SESSION_TOKEN_VALUE" && -r "$HOME/.ironclaw/session.json" ]]; then
  NEARAI_SESSION_TOKEN_VALUE="$(
    python3 - <<'PY'
import json
import os

session_path = os.path.expanduser('~/.ironclaw/session.json')
try:
    with open(session_path) as handle:
        print(json.load(handle).get('session_token', ''))
except Exception:
    print('')
PY
  )"
fi

case "$GATEWAY_HOST" in
  127.0.0.1|localhost|::1) ;;
  *)
    if [[ "${IRONCLAW_ALLOW_NONLOCAL_BIND:-0}" != "1" ]]; then
      echo "Refusing to bind IronClaw to '$GATEWAY_HOST' by default." >&2
      echo "Use GATEWAY_HOST=127.0.0.1 for local development, or set IRONCLAW_ALLOW_NONLOCAL_BIND=1 explicitly." >&2
      exit 1
    fi
    ;;
esac

printf "%s\n" "$GATEWAY_AUTH_TOKEN" > "$TOKEN_FILE"
chmod 600 "$TOKEN_FILE"

if [[ ! -d "$IRONCLAW_REPO" ]]; then
  echo "IronClaw repo not found: $IRONCLAW_REPO" >&2
  echo "Set IRONCLAW_REPO=/path/to/ironclaw and try again." >&2
  exit 1
fi

if ! command -v screen >/dev/null 2>&1; then
  echo "screen is required to keep IronClaw running detached." >&2
  exit 1
fi

if [[ ! -x "$IRONCLAW_BIN" ]]; then
  echo "Building IronClaw..."
  (cd "$IRONCLAW_REPO" && cargo build --bin ironclaw)
fi

if screen -list | grep -q "[.]$SCREEN_NAME[[:space:]]"; then
  screen -S "$SCREEN_NAME" -X quit || true
fi

existing_pid="$(lsof -tiTCP:"$GATEWAY_PORT" -sTCP:LISTEN 2>/dev/null | head -n 1 || true)"
if [[ -n "$existing_pid" ]]; then
  existing_cmd="$(ps -p "$existing_pid" -o comm= 2>/dev/null || true)"
  if [[ "$existing_cmd" == *ironclaw* ]]; then
    kill "$existing_pid" || true
    for _ in {1..20}; do
      lsof -tiTCP:"$GATEWAY_PORT" -sTCP:LISTEN >/dev/null 2>&1 || break
      sleep 0.25
    done
  else
    echo "Port $GATEWAY_PORT is already in use by PID $existing_pid ($existing_cmd)." >&2
    exit 1
  fi
fi

: > "$LOG_FILE"
chmod 600 "$LOG_FILE"

write_export() {
  local key="$1"
  local value="$2"
  printf 'export %s=%q\n' "$key" "$value"
}

{
  echo "# Generated by start-ironclaw-gateway.sh. Do not commit."
  write_export IRONCLAW_REPO "$IRONCLAW_REPO"
  write_export IRONCLAW_BIN "$IRONCLAW_BIN"
  write_export LOG_FILE "$LOG_FILE"
  write_export GATEWAY_ENABLED true
  write_export GATEWAY_HOST "$GATEWAY_HOST"
  write_export GATEWAY_PORT "$GATEWAY_PORT"
  write_export GATEWAY_AUTH_TOKEN "$GATEWAY_AUTH_TOKEN"
  write_export NEARAI_MODEL "$NEARAI_MODEL"
  write_export CLI_ENABLED false
  write_export CLI_MODE repl
  write_export ENGINE_V2 true
  write_export IRONCLAW_AUTO_APPROVE "$IRONCLAW_AUTO_APPROVE"
  write_export NEARAI_SESSION_TOKEN "$NEARAI_SESSION_TOKEN_VALUE"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

cat > "$RUNNER_FILE" <<'SH'
#!/bin/zsh
  set -euo pipefail
  ENV_FILE="${1:?env file required}"
  if [[ ! -r "$ENV_FILE" ]]; then
    echo "IronClaw env file is missing or unreadable: $ENV_FILE" >&2
    exit 1
  fi
  source "$ENV_FILE"
  export RUST_LOG="${RUST_LOG:-ironclaw=info,tower_http=warn}"
  cd "$IRONCLAW_REPO"
  args=(run --no-onboard)
  if [[ "${IRONCLAW_AUTO_APPROVE:-0}" == "1" ]]; then
    args+=(--auto-approve)
  fi
  exec "$IRONCLAW_BIN" "${args[@]}" >> "$LOG_FILE" 2>&1
SH
chmod 700 "$RUNNER_FILE"

screen -dmS "$SCREEN_NAME" /bin/zsh "$RUNNER_FILE" "$ENV_FILE"

for _ in {1..40}; do
  if curl -fsS "http://$HEALTH_HOST:$GATEWAY_PORT/api/health" >/dev/null 2>&1; then
    listener_pid="$(lsof -tiTCP:"$GATEWAY_PORT" -sTCP:LISTEN 2>/dev/null | head -n 1 || true)"
    [[ -n "$listener_pid" ]] && echo "$listener_pid" > "$PID_FILE"
    echo "IronClaw local-development gateway is running at http://$GATEWAY_HOST:$GATEWAY_PORT"
    if [[ "$GATEWAY_HOST" != "127.0.0.1" && "$GATEWAY_HOST" != "localhost" && -n "$LAN_HOST" ]]; then
      echo "Local-dev LAN URL: http://$LAN_HOST:$GATEWAY_PORT"
    fi
    echo "Gateway token: generated and saved outside the repo at $TOKEN_FILE"
    echo "Auto-approve: $([[ "$IRONCLAW_AUTO_APPROVE" == "1" ]] && echo enabled || echo disabled)"
    echo "NEAR AI model: $NEARAI_MODEL"
    echo "Log: $LOG_FILE"
    exit 0
  fi
  sleep 0.25
done

echo "IronClaw did not become healthy. Recent log:" >&2
tail -n 80 "$LOG_FILE" >&2 || true
exit 1
